name: Dotnet
on: [push]

jobs:
  NugetRestore:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: NuGet restore
      run: nuget restore

  MsBuild:
    needs: NugetRestore
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: Build solution **\*.sln
      run: msbuild '' /p:OutputPath=${{ github.workspace }}\bin /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem  /p:PrecompileBeforePublish=true /p:EnableUpdateable=false /p:DebugSymbols=true  /p:UseMerge=false /p:DeleteAppCodeCompiledFiles=True /p:DeleteExistingFiles=True  /p:WDPMergeOption=CreateSeparateAssembly /p:UseFixedNames=true

